module.exports = [
  {
    time: '2019-05-11 8:00:00 AM',
    track: 'Keynote',
    room: 1,
    topic: 'other',
    speaker: 'Jeff Smith',
    image: 'https://secure.gravatar.com/avatar/f959e45f682c75f5a473dee025027488?s=250&d=https%3A%2F%2Fwww.devopsdays.org%2Fevents%2F2018-chicago%2Fspeakers%2Fjeffery-smith.png&f=y',
    title: 'What is Culture?',
    tags: ['other'],
    level: 100,
    description: 'Culture has been talked about quite a bit, especially within the DevOps space. People are always talking about building a great culture, fostering a great culture. But ultimately what does that mean? We view culture as a organizational trait, but culture exists at multiple levels within an organization. What makes a culture great? How do you build a culture? How do you identify a bad versus a good culture? In this talk well dive into the specific components of a culture and how it operates within different levels of the organization. Well come up with specific steps that you can take to foster that culture in your teams and in your organization. Hiring for fit is an important aspect of maintaining a company culture. Ensuring that your interview process takes this into account, while not limiting the types of personalities that your company brings on is also key!'
 },
  {
    time: '2019-05-11 09:15:00 PM',
    track: 'AI & Data Science',
    room: 6,
    topic: 'other',
    speaker: 'Brian Goodwin',
    image: 'https://secure.gravatar.com/avatar/debc90b3d6ddb02c1b2a0d6f6d32cb2b?s=250&d=mm',
    title: "Optimization through Genetic Mutations",
    tags: ['other'],
    level: 100,
    description: 'Genetic algorithms are variants of evolutionary algorithms that search a parameter space using an adaptive heuristic. Existing knowledge of certain biological mechanisms have largely aided in their design, which make use of principles in genetics and natural selection. This type of algorithm seeks to arrive at a optimized state according to specified criteria by exploring its (large) parameter spaces and is therefore inherently computationally intensive. Although the list of applications for genetic algorithms is growing, they are most commonly used for optimization problems. We aim to 1) give an overall introduction to the idea of genetic algorithms drawing parallels with genetics, 2) discuss cases where this algorithm class will be especially useful, and 3) demonstrate an implementation using computational tools like Databricks in Azure.'
  },
  {
    time: '2019-05-11 10:45:00 AM',
    track: 'AI & Data Science',
    room: 6,
    topic: 'other',
    speaker: 'Pete Haas',
    image: 'https://secure.gravatar.com/avatar/35a2138fed3e4eacea76855e53060214?s=250&d=mm',
    title: "Hello, I'm your AI Assistant",
    tags: ['other'],
    level: 200,
    description: 'The GUI interface was an answer to the command line, followed by the internet browser. Then, mobile computing allowed users to take their computing with them. Now, we are entering an exciting era where these technologies can understand you and perform tasks on your behalf. Introducing the AI assistant! Soon, it will be natural for us to be aided in our daily lives by one of the many platforms to answer questions, and perform tasks on our behalf. Book reservations, ask questions using your voice, interact with a totally personalized assistant to help get things done. All the large players are fighting to own the home, the car, and the office. Want to see how ambient computing and mobile phone assistants work? Check out this session from a developer building voice experiences for the major platforms!'
  },
  {
    time: '2019-05-11 01:00:00 PM',
    track: 'AI & Data Science',
    room: 6,
    topic: 'other',
    speaker: 'Ilia Smirnov',
    image: 'https://secure.gravatar.com/avatar/1810624ad18bea31160bb116bd5e9580?s=250&d=http%3A%2F%2Fwww.gravatar.com%2Favatar%2F0aa4d3c3cdbce3cc3df6003cac70c63e%3Fs%3D250%26%26r%3DG&f=y',
    title: "Let's say it",
    tags: ['other'],
    level: 100,
    description: 'With the recent advent of smart devices, speech-driven interfaces are becoming more and more common. Though technologies behind them have been around for decades, not many developers are familiar with them due to very specialized application scope, like accessibility. The presentation covers the history of text-to-speech (TTS) systems, basic algorithms including most common "unit selection" synthesis, typical issues TTS designers are facing, Speech Synthesize Markup Language (SSML) and common APIs like .Net Speech.'
  },
  
  {
    time: '2019-05-11 02:30:00 PM',
    track: 'AI & Data Science',
    room: 6,
    topic: 'other',
    speaker: 'Wendy Istvanick',
    image: 'https://secure.gravatar.com/avatar/730e68fed5304c912da654e057ec1d0d?s=250&d=mm',
    title: "Don't Get Lost in the Random Forest",
    tags: ['other'],
    level: 200,
    description: 'As more and more data is amassed, focus has increased on getting information out of the data. Data Science is becoming mainstream. Machine learning can play a key role when using Data Science to find a solution to a problem. There are numerous algorithms used to programmatically learning about and from data. Random Forest is one that is both popular and powerful. In this talk I present the theory behind Random Forests and the Decision Trees form which they are made. Consider this theory your compass. I then move on to examine the attributes of a small data set. Consider the values and the relationships between them as your map. Finally, with our compass and map in hand I look at a Random Forest implementation that makes predictions from the data without getting lost.'
  },
  {
    time: '2019-05-11 04:00:00 PM',
    track: 'AI & Data Science',
    room: 6,
    topic: 'other',
    speaker: 'Bruno Capuano',
    image: 'https://secure.gravatar.com/avatar/4eb7ca76a3138cf9959d39f0694c6f8a?s=250&d=mm',
    title: "Deep Learning for everyone?  Challenge Accepted!",
    tags: ['.net'],
    level: 200,
    description: 'You probably read a lot about Machine Learning and Deep Learning these days; however, if you are a standard developer (like me), is hard to find a way to start with ML or DL. So, lets avoid learning specific ML languages and tools, and lets have some fun using a popular language like C# to create a DL model. And, lets also try to run this model in a popular device like a Raspberry Pi (why not?). We may add some cloud, and some IoT pieces to the scene, however, keep in mind that during this session the idea is to LEARN and HAVE FUN. Creating something from zero is one of the best ways to understand how Deep Learning works!'
  },
  {
    time: '2019-05-11 09:15:00 AM',
    track: 'Career',
    room: 4,
    topic: 'other',
    speaker: 'Joel Karr',
    image: 'https://secure.gravatar.com/avatar/fa71233381dee830f56fa17d03a69293?s=250&d=https%3A%2F%2Flh3.googleusercontent.com%2F-_7B5XBzFPeU%2FAAAAAAAAAAI%2FAAAAAAAAbx4%2FO_Jrv23Hk4Y%2Fs120-c%2Fphoto.jpg&f=y',
    title: "Developer's Playbook",
    tags: ['other'],
    level: 100,
    description: "Sometimes writing code can seem like a never ending hustle to keep up with the latest language or library. Often times we find ourselves searching stack overflow or blogs looking for someone who encountered the exact same problem that we face. We may even start to feel the effects of Impostor's Syndrome when we doubt our own skills. In this talk we will focus on how to move from knowledge to understand to a state of flow. We will break down how to build a solid mental model to make decisions quickly and efficiently. Identifying when new information presents itself to re-evaluate. As you build your own Developer's Playbook, we will talk about how to focus on small details to optimize the way we write code with constant improvement. Clearly identifying what you know to be more predictable and efficient so that you can spend more time in pursuit of greatness. You may even start to see code without your eyes!"
  },
  {
    time: '2019-05-11 10:45:00 AM',
    track: 'Career',
    room: 4,
    topic: 'other',
    speaker: 'Mike Wydra',
    image: 'https://secure.gravatar.com/avatar/4c863d83d8f0b0f48a98e5a72a3bfbc1?s=250&d=mm',
    title: "Stress Regulation for the Knowledge Worker",
    tags: ['other'],
    level: 100,
    description: "This talk will cover a mixture of techniques that will help any knowledge worker better cope with the stresses of everyday life and career. More and more each day, it is being found that mindfulness and meditation have great positive impact both in personal and professional life. Additionally, workspaces have been constructed to maximize productivity, but minimize the health of a worker. Exercises covered with be simple breathwork mindfulness/meditation, and stretches from physical therapists to combat prolonged seating at a desk. The background and science of why these techniques works will be covered. And other half will be an applied demonstration and guidance through exercises."
  },
  {
    time: '2019-05-11 01:00:00 PM',
    track: 'Career',
    room: 4,
    topic: 'other',
    speaker: 'Michelle Diaz',
    image: 'https://secure.gravatar.com/avatar/4c863d83d8f0b0f48a98e5a72a3bfbc1?s=250&d=mm',
    title: "Building your Peronal Brand",
    tags: ['other'],
    level: 100,
    description: "This talk is about HR in the workplace and how it is important for you to talk with your HR."
  },
  {
    time: '2019-05-11 02:30:00 PM',
    track: 'Career',
    room: 4,
    topic: 'other',
    speaker: 'Phil Vuollet',
    image: 'https://secure.gravatar.com/avatar/4c863d83d8f0b0f48a98e5a72a3bfbc1?s=250&d=mm',
    title: "Bridging the Gap Between Devs and the Business",
    tags: ['other'],
    level: 100,
    description: "Developers (and IT folks in general) can be so far removed from the business that it feels like we're in our own world. How do we bridge that gap and form an understanding between business and technology? Let's start by learning a bit about business so we have a perspective on what's going on in the minds of business managers. Then, we have a good reference point for decision making. But where do we go from there? To find out, I decided to take an MBA program and start a business (at the same time). In this talk, I'll share some of the newfound perspectives I have as a software developer taking MBA courses. I'll also share what it's been like so far to own a single person small business. Hopefully, you'll be inspired to pave your own way to the American dream!"
  },
  {
    time: '2019-05-11 04:00:00 PM',
    track: 'Career',
    room: 4,
    topic: 'other',
    speaker: 'Jim Kusumpa',
    image: 'https://secure.gravatar.com/avatar/4c863d83d8f0b0f48a98e5a72a3bfbc1?s=250&d=mm',
    title: "Remote Development Workforce - Discovery, Reflection and Suggestions",
    tags: ['other'],
    level: 100,
    description: "I would like to talk about Remote Development Workforce. What works well? What doesn't work well? What we discovered at PCTY? End with some suggestions on how to make a great remote employee, boss or cultivator."
  },
  {
    time: '2019-05-11 09:15:00 AM',
    track: 'Gaming',
    room: 1,
    topic: 'other',
    speaker: 'Jason Von Rudden',
    image: 'https://secure.gravatar.com/avatar/59b3369737a0159c97cb947e9009cff0?s=250&d=mm',
    title: "Solution to a Stalled Technical Career",
    tags: ['other'],
    level: 100,
    description: "There are two kinds of IT professionals, the kind who goes to work and when the day is done they go home and the only time they learn new skills is when their employee provides the training and they wait for the company to manage their career for them. After 10 years in their career, they think that they have 10 years of experience however in realty they just have 1 year of experience repeated 10 times and they are stuck re-living the past and they may have not realized it and their career has stalled out until they start failing the technical interview questions for a new job. The other kind of IT professional is the ones who realize they need to manage their own career and take steps to build relationships, learn new skills, invest in their career, and are constantly making technology course corrections in their career that take them to the next level and then reap the rewards of all their hard work. **The Solution** * In your career there are three powers that you have: Expertise Power, Role Power, and Relationship Power. Learn which power is the most important power and rules them all. * Communication is key and understanding the DISC behavior assessment model will unlock unlimited potential in your career. * Be active in your IT community including attending or leading local meetups or IT conferences to network with other IT professionals and learn new skills."
  },
  {
    time: '2019-05-11 10:45:00 AM',
    track: 'Gaming',
    room: 1,
    topic: 'other',
    speaker: 'Andy Yun',
    image: 'https://secure.gravatar.com/avatar/37863797ee44c8521a4375c3a3153760?s=250&d=http%3A%2F%2Fwww.gravatar.com%2Favatar%2F37863797ee44c8521a4375c3a3153760%3Fs%3D250%26%26r%3DG&f=y',
    title: "Building Winning Business Cases",
    tags: ['other'],
    level: 100,
    description: "Are you a technologist who sometimes has a difficult time getting the business to sign off on the things you need? Perhaps you have a great idea to improve something, but management just does not see the value that you see. Come to this session and you'll learn some new techniques on how to engage your busines counterparts, present an effective business case, and get them on your side!"
  },
  {
    time: '2019-05-11 01:00:00 PM',
    track: 'Gaming',
    room: 1,
    topic: 'other',
    speaker: 'Mark Lassoff',
    image: 'https://secure.gravatar.com/avatar/bcfb51eb8712b401312f7a03869df034?s=250&d=mm',
    title: "HADOUKEN! JavaScript Game Development",
    tags: ['other'],
    level: 100,
    description: "HTML5 presents a great opportunity to create browser-based games that work across the array of tablet and smartphone based devices. In the near future, as the device environment becomes more diverse, developers will begin to adopt standards that work across all devices. With HTML5, Javascript and the free createJS engine, surprisingly sophisticated games can be created. In this workshop session, you'll be invited to code along with the instructor as you create a basic game and deploy it to a mobile environment. The games graphical and audio assets will be provided to you as you learn the techniques to create HTML5 based game that includes sprite-based graphics, audio, animations and more. What will attendees learn? Understand the Tools, Environment and Libraries used for HTML5 Game Programming HTML5 Game Development Workflow How to Create and Load Sprites (Canvas Display Objects) Object Nesting: How to Create an Object Hierarchy Asset Preloading: Make sure Game Assets are Available When Needed Tweens and Tween Sequences: Creating Animations Programmatically Audio: Creating Audio that will Work across Devices Much More"
  },
  {
    time: '2019-05-11 02:30:00 PM',
    track: 'Gaming',
    room: 1,
    topic: 'other',
    speaker: 'Travis Feirtag',
    image: "https://secure.gravatar.com/avatar/294862a9a0f96a399314fbec8697cbf0?s=250&d=mm",
    title: "Play is Older than Culture : Game Design & Prototyping with Unity and .NET",
    tags: ['other'],
    level: 200,
    description: "A journey into game design with the latest .NET tools. This presentation will go over the fundamentals of game design and prototyping. I will share with you resources I have found that have been helpful to me. We will prototype a game using Unity and Visual Studio 2019. There are so many styles of games out there. Let's see how we can use these tools to help us with our game design."
  },
  
   {
    time: '2019-05-11 09:15:00 AM',
    track: 'Cloud & Containers',
    room: 2,
    topic: 'web',
    speaker: 'Matthew McNew',
    image: 'https://secure.gravatar.com/avatar/baae91663a1e078c6c9a5c180d637f42?s=250&d=mm',
    title: 'How Cloud Native Buildpacks can help you easily build Container Images',
    tags: ['cloud','devopps'],
    level: 300,
    description: 'Application containers are used everywhere these days, in development, in CI/CD and on platforms such as kubernetes. However, to leverage the container ecosystem developers need to convert their source code to working images. This surprisingly complicated task often results, in the unnecessary toil of maintaining custom Dockerfiles. However, with open source Cloud Native Buildpacks, developers can easily build small, fast reproducible docker images without the pitfalls of Dockerfiles. This session will examine why application containers are important and how Dockerfiles and other non-buildpack solutions introduce unnecessary complexity. Instead, we will demonstrate how it is possible to leverage buildpacks to build docker images with a single command. Attendees will learn how the growing buildpack ecosystem provides support for everything from .Net to Node. Finally, for those security-minded developers, we will look at how buildpacks enable painless OS-level dependency upgrades.'
  },
  {
    time: '2019-05-11 10:45:00 AM',
    track: 'Cloud & Containers',
    room: 2,
    topic: 'web',
    speaker: 'Paul Hacker',
    image: 'https://secure.gravatar.com/avatar/f627a2770ce598a0dbd59a79b73ec3f4?s=250&d=mm',
    title: 'Deploying Infrastructure - Azure Resource Management',
    tags: ['cloud','devopps','ALM'],
    level: 300,
    description: 'Does it take you days to deploy your infrastructure? In this session we are going to introduce you to Azure Resource Manager and demonstrate how we create Azure Resource Manager (ARM) templates using Visual Studio 2017 and then deploy the infrastructure to Azure in minutes. We are going to peek under the covers of the ARM templates to show you what is going on inside the template and why you should be implementing it today. We will look at the Azure portal and walk through the infrastructure we deployed. Lastly we will look at the Azure Resource Template Visualizer and show you a great way to use it to get you started with ARM template creation.'
  },
  {
    time: '2019-05-11 01:00:00 PM',
    track: 'Cloud & Containers',
    room: 2,
    topic: 'web',
    speaker: 'Pratik Sampat',
    image: 'https://secure.gravatar.com/avatar/16b7064040ee70d61858ca41435ea80c?s=250&d=mm',
    title: 'Kubernetes Jargon for the Web Developer',
    tags: ['cloud','devopps','ruby','web'],
    level: 100,
    description: 'Kubernetes is the leading container orchestration framework for automating application deployment, scaling, and management. Being a developer, I know my application code inside out but having it production-ready on a high availability platform wasnt part of the job description. Maybe youve heard of this magical platform and just need a gentle introduction without all the complicated documentation. In this session, you will learn the basics from a developers point of view and deploy an application to your own Kubernetes cluster.'
  },
  {
    time: '2019-05-11 02:30:00 PM',
    track: 'Cloud & Containers',
    room: 2,
    topic: 'web',
    speaker: 'Jim Szubryt',
    image: 'https://secure.gravatar.com/avatar/542f039f908d37ea5215fc94380babf1?s=250&d=mm',
    title: 'Azure Containers: Choices, Choices, Choices',
    tags: ['alm','cloud','devops','web'],
    level: 100,
    description: 'Microsoft Azure has many Container choices: Azure Container Service, Containers in Service Fabric, Azure Kubernetes Services and Container Instances. What is the right choice? How does Kubernetes fit in? Do I need to know Docker to use any of these options?'
  },
  {
    time: '2019-05-11 04:00:00 PM',
    track: 'Cloud & Containers',
    room: 2,
    topic: 'web',
    speaker: 'Adam Kerr',
    image: 'https://secure.gravatar.com/avatar/bb7124718bbe0d8ec4ffca37c8fe2c4b?s=250&d=mm',
    title: 'C# and AWS Lambda - Serverless Beyond The Demo!',
    tags: ['.net','mvc','web'],
    level: 300,
    description: 'Its easy to stand up a new serverless API in AWS Lamba; the built-in templates can have your api deployed in minutes at a price point bordering on free! Ive spent the last two years building a full serverless application from the ground up. Now that youre excited to build your next project on Amazons serverless platform, its time to learn about all the little pieces the demos didnt tell you. While the examples focus on the Microsoft stack, the lessons shared are broadly applicable. In this session, we will learn about: - Integrating your api with other serverless offerings for expanded capabilities - Serverless advantages in a microservice ecosystem - Increasing performance when there is no server - Debugging serverless applications - Handling file up- and downloads - Managing long-running requests - Deploying to AWS Lambda using the Dotnet CLI and Visual Studio Team System - Updating configuration information without redeployment, without access to the file system - AWS Fargate, when Lamda isnt enough'
  },
  {
    time: '2019-05-11 09:15:00 AM',
    track: 'Javascript',
    room: 8,
    topic: 'javascript',
    speaker: 'Justin Montgomery',
    image: 'https://secure.gravatar.com/avatar/712d832cab0856d26ac5132c1560ccdb?s=250&d=mm',
    title: 'Avoid reducing your project to ashes with Reach/Redux',
    tags: ['javascript','web'],
    level: 200,
    description: "React and Redux seem like a match made in heaven, but it’s easy to get caught in the hype and reduce your project to ashes if you don’t take the proper actions. We will point out the common mistakes developers make when working with a React/Redux application and lay out the proper options one should consider when building an application. We will focus both on the tools available for productivity and the best libraries and patterns to adopt."
  },
  {
    time: '2019-05-11 10:45:00 AM',
    track: 'Javascript',
    room: 8,
    topic: 'javascript',
    speaker: 'Rosalind Wills',
    image: 'https://secure.gravatar.com/avatar/9a54d2d18db64b931e72527a15bbc4fa?s=250&d=mm',
    title: 'Intro to Redux State Management in Javascript Applications',
    tags: ['javascript','web'],
    level: 200,
    description: 'Redux is a self-proclaimed “predictable state container” for managing application state in Javascript apps. If you’re in the front-end development world, you’ve probably heard of it; it’s hard to miss, particularly in the React ecosystem. If you haven’t had to use it for a project yet, though, you may find its concepts somewhat tricky to understand, or intimidating to integrate into an existing workflow. In this talk, I will be going over the core principals of Redux and what makes them awesome for debugging and managing application complexity, as well as going through a quick demo with a simple React application to show how you might apply Redux state management to an existing app.'
  },
  {
    time: '2019-05-11 01:00:00 PM',
    track: 'Javascript',
    room: 8,
    topic: 'javascript',
    speaker: 'Eric Potter',
    image: 'https://secure.gravatar.com/avatar/5419f3f5fec50cfcfd0c7d4a18ae25ca?s=250&d=mm',
    title: 'TypeScript: Beyond the basics',
    tags: ['javascript','web'],
    level: 200,
    description: 'TypeScript is proving to be a very valuable addition to the world of modern web development. But what can it do for you beyond just adding types to your variables and parameters? In this talk, we look at some of the more advanced features in the language that can help you deliver valuable solutions in less time. In this session you will learn about some of the new features in TypeScript 3.3. You will also learn about union types and intersection types. You will learn how your code can benefit from Mixins and other language features that you may not be aware of.'
  },
  {
    time: '2019-05-11 02:30:00 PM',
    track: 'Javascript',
    room: 8,
    topic: 'javascript',
    speaker: 'Chris Courtney',
    image: 'https://secure.gravatar.com/avatar/1d14af62443ebeef7d8b022c03cd9ab1?s=250&d=mm',
    title: 'Up and running with Gatsby.js',
    tags: ['javascript','web'],
    level: 200,
    description: "With the JAMstack movement continuing to grow and new tools appearing each week, the question isn't if when to start — it's where to start. In this session, we'll dig into Gatsby to uncover how it is different from the others and uncover some of the next steps you can take to get your first projects public before the day is over."
  },
  {
    time: '2019-05-11 04:00:00 PM',
    track: 'Javascript',
    room: 8,
    topic: 'javascript',
    speaker: 'Emily Drevets',
    image: 'https://secure.gravatar.com/avatar/9759d1ea082fcbaae8cc9b4a3fb8eb36?s=250&d=mm',
    title: 'Understanding JavaScript Bundling From the Inside-Out: Webpack Loaders and Plugins',
    tags: ['javascript','web','other','security'],
    level: 100,
    description: "Webpack is a widely-used bundling and code transformation tool used in JavaScript applications. If you've worked on or near the front end of a JS web application, it's likely that you've at least heard of it. But have you ever wondered what Webpack is really doing under the hood? In this session, we'll take a look at how this technology works, why it works the way that it does, and how we can extend it for our own use cases and purposes. You will gain an appreciation for how fascinating this Node tool is and maybe even get some ideas for contributing to the project or building your own code transformation tools."
  },
  {
    time: '2019-05-11 09:15:00 AM',
    track: 'Language',
    room: 5,
    topic: 'language',
    speaker: 'Fawad Halim',
    image: 'https://secure.gravatar.com/avatar/f3bb3af59760a8beb13d406e7644933e?s=250&d=https%3A%2F%2Fwww.gravatar.com%2Fuserimage%2F19528768%2F45a2025f21cdb3c6f611fb575d04e4e5%3Fsize%3D250&f=y',
    title: 'Gotta Go',
    tags: ['other','go'],
    level: 200,
    description: "The Go Programming Language is rapidly becoming the language of choice for distributed systems. In this presentation, we'll look at the aspects of the language and its ecosystem that make it so compelling for building core cloud applications. The presentation will be very demo focused. Some programming background is required."
  },
  {
    time: '2019-05-11 10:45:00 AM',
    track: 'Language',
    room: 5,
    topic: 'language',
    speaker: 'Zaynaib Giwa',
    image: 'https://secure.gravatar.com/avatar/997f7139cdc73ba1a8254295ec22ffd2?s=250&d=mm',
    title: 'D3.js for beginners',
    tags: ['other','d3'],
    level: 100,
    description: "The D3 library has a high learning curve. This workshop will teach the fundamentals of D3.js version 4 from a beginners perspective. This workshop will give a brief overview of SVGs , data binding, and plotting basic graphs such as bar charts,line, and scatter graphs with the D3 library."
  },
   {
    time: '2019-05-11 01:00:00 PM',
    track: 'Language',
    room: 5,
    topic: 'language',
    speaker: 'Chi Huynh',
    image: 'https://secure.gravatar.com/avatar/df2943330f459b3ee718f93de42b6296?s=250&d=mm',
    title: 'Pharo (Smalltalk) Programming Language',
    tags: ['other','d3'],
    level: 100,
    description: "Smalltalk is a pure object oriented language created by a research group led by Alan Kay at Xerox PARC. It was where Steve Jobs was amazed and inspired by the graphical user interface on the Alto computers, which was later implemented for the Apple Lisa, that failed for its expensive price and low performance. Pharo is an open source language inspired by Smalltalk. It is a live programming language and is its own integrated development environment, so it is kind of its own OS! Pharo full syntax fits on one postcard. There are no constructors, no types declaration. Pharo is ALL about objects and messages. The message is this: Pharo is yours: Pharo is made by an incredible community, with more than 100 contributors for the last revision of the platform and hundreds of people contributing constantly with frameworks and libraries. I am a VERY beginner. I would not be able to talk to you like a person with 3 years of experience, even. However, I can show you how I started learning Pharo and present to you a VERY unique experience of programming! We can start by me showing you the Phao environment, how to create classes and methods, and how to test. Finally, if you want to learn, I can show you the MOOC and other resources."
  },
  {
      time: '2019-05-11 02:30:00 PM',
    track: 'Language',
    room: 5,
    topic: 'language',
    speaker: 'Michael Rosack',
    image: 'https://secure.gravatar.com/avatar/21e0d0e881448fe6d4d32deeb93fa7f8?s=250&d=mm',
    title: 'C# in the browser with Bridge.NET!',
    tags: ['javascript','web'],
    level: 200,
    description: 'A big reason Javascript has become so popular is that you can write it on both the front AND the back end, sharing code where it makes sense between the two. For those of us that love C#, we’ve had to leave our favorite language on the shelf when were coding front-end logic. But what if I said you could have your cake and eat it too, without waiting for things like Webassembly and Blazor to mature? Bridge.NET is a mature open-source project that will take C# code and transpile it to Javascript, allowing you to write business logic once and use it on both the front and back end! We’ll set up a sample project and show a real world case study of how you can use bridge to make your front end more responsive and powerful without coding things twice!'
  },
  {
    time: '2019-05-11 04:00:00 PM',
    track: 'Language',
    room: 5,
    topic: 'language',
    speaker: 'Michael Fazio',
    image: 'https://secure.gravatar.com/avatar/169c977d7c71e35679d4b1e1a5cf8bfc?s=250&d=http%3A%2F%2Fwww.gravatar.com%2Favatar%2F169c977d7c71e35679d4b1e1a5cf8bfc%3Fs%3D250%26%26r%3DG&f=y',
    title: "Kotlin - Less Code, More Fun",
    tags: ['java'],
    level: 100,
    description: "tl;dr - Write less (but safer!) code in your Android apps or any JVM-based projects Ever work on an Android app and tire of all the boilerplate code? Or spend hours chasing down NullPointerExceptions in your Java app? Enter Kotlin, JetBrains' new(ish) free, open-source programming language that targets the JVM. This means you can use it everywhere you use Java, but with a modern, succinct syntax. For native Android developers, Kotlin is not only available, but it's now considered a first-class language. You're able to write an app completely with Kotlin, or switch over entire components, or even just change your models to Kotlin's data classes (which removes a TON of boilerplate code.) Oh, and for anyone using Java elsewhere, you can add in Kotlin code to your existing application. Kotlin is 100% interoperable with Java, meaning all your existing code/libraries/tests will work with any Kotlin code you write. Doing JavaScript development? Kotlin can be transpiled into ES5, and there are even libraries available to use React or Angular with Kotlin. C# dev working on any kind of Java project? You'll feel much more at home with Kotlin, given features like nullable types, properties (rather than getters/setters), and extension methods. We'll walk through Kotlin's features, check out the syntax, and understand why Kotlin is a great choice for a huge variety of projects."
  },
  
  {
    time: '2019-05-11 09:00:00 PM',
    track: 'Mobile & IoT',
    room: 9,
    topic: 'web',
    speaker: 'Lance Larsen',
    image: 'https://secure.gravatar.com/avatar/5e9dde45d5f3207143d9b60b3adb4108?s=250&d=mm',
    title: 'Azure Spatial Anchors: Building a Shared Mixed Reality across Devices (Hololens, iOS & Android)',
    tags: ['.net','cloud','mobile'],
    level: 100,
    description: "Azure Spatial Anchors is a cross-platform developer service that allows you to create mixed reality experiences using objects that persist their location across devices over time. This enables developers to build apps that map, designate and recall precise points of interest that are accessible across HoloLens, iOS and Android devices. It allows people in the same place to participate in multi-user mixed reality applications. For example, two people can start a game of mixed reality chess by placing a virtual chess board on a table. Then, by pointing their device at the table, they can view and interact with the virtual chess board together. One of the people can use an iPhone while the other can use an Android device. We'll explore the exciting new Mixed Reality world where Visual Studio + Unity makes these amazing cross-device immersive experiences the Reality possible today! Interested in being the employee or consultant that becomes the go-to guy or gal that Enterprises look to for leading these projects? Or starting your own company working on this future focused technology? Join Lance Larsen (Microsoft MVP) and organizer of MADdotNET (Madison's .NET User Community) in building the skills you will need for the growing global Augmented, Virtual and Mixed Reality Markets that are projected to reach $814.7 Billion By 2025."
  },
  {
    time: '2019-05-11 10:45:00 AM',
    track: 'Mobile & IoT',
    room: 9,
    topic: 'web',
    speaker: 'Chester Hartin',
    image: 'https://secure.gravatar.com/avatar/46f7d9097d727eb26328bcc649e5c940?s=250&d=http%3A%2F%2Fwww.gravatar.com%2Favatar%2F46f7d9097d727eb26328bcc649e5c940%3Fs%3D250%26%26r%3DG&f=y',
    title: 'Xamarin 101 – what you need to know to get started today',
    tags: ['.net','mobile','mobile'],
    level: 100,
    description: "Do you have a great idea for an app? Want to wow your boss with a great mobile app for the company? Don’t want to learn java or obj-c/swift? Xamarin could be right for you! In this talk I will demonstrate the basics of Xamarin Forms as well as demonstrating 3 sample apps: Hello World, Tic-Tac-Toe, and an API-backed Food Tracker. In addition, I will provide a handy guide to go from idea to store."
  },
  {
    time: '2019-05-11 01:00:00 PM',
    track: 'Mobile & IoT',
    room: 9,
    topic: 'web',
    speaker: 'Bruno Capuano',
    image: 'https://secure.gravatar.com/avatar/4eb7ca76a3138cf9959d39f0694c6f8a?s=250&d=mm',
    title: 'How a PoC at home can scale to Enterprise Level using Custom Vision APIs',
    tags: ['.net','cloud'],
    level: 100,
    description: "It all started with a DIY project to use Computer Vision for security cameras at home. A custom Machine Learning model is the core component used to analyze pictures to detect people, animals and more in a house environment. The AI processing is performed at the edge, in dedicated hardware and the collected information is stored in the cloud. The same idea can be applied to several CCTV scenarios, like parking lots, train stations, malls and more. However, moving this into enterprise scale brings a set of challenges, which are going to be described and explained in this session."
  },
  {
    time: '2019-05-11 02:30:00 PM',
    track: 'Mobile & IoT',
    room: 9,
    topic: 'web',
    speaker: 'Justin Maurer',
    image: 'https://secure.gravatar.com/avatar/d288d44d5ccc50ee7b06aed9c52e4e30?s=250&d=mm',
    title: 'Conducting Music with React Native and Machine Learning',
    tags: ['mobile'],
    level: 200,
    description: "Today's smartphones have all that's necessary to be an electronic conductors baton. In this talk, I'll walk through how you can use accelerometers and machine learning to detect music conducting gestures that affect the tempo (BPM) and dynamic range of MIDI music."
  },
  
  {
    time: '2019-05-11 04:00:00 PM',
    track: 'Mobile & IoT',
    room: 9,
    topic: 'web',
    speaker: 'John Adali',
    image: 'https://secure.gravatar.com/avatar/f4ffd9ac4b9d373167a0a7ea8d16e268?s=250&d=mm',
    title: 'Azure IoT Edge: Push Your Solutions Close to (but not off) the Edge',
    tags: ['.net','cloud','security','web'],
    level: 100,
    description: 'Leverage the unused power of your devices by utilizing an Internet of Things (IoT) solution with Azure IoT Edge. We will discuss what Azure IoT Edge provides, along with demos on how you can deliver cloud intelligence locally on your devices. You will learn the benefits of using Azure IoT Edge, as well as how to centrally manage it all in the cloud.'
  },
  
   {
    time: '2019-05-11 09:15:00 PM',
    track: 'Practices',
    room: 7,
    topic: 'practices',
    speaker: 'David Giard',
    image: 'https://secure.gravatar.com/avatar/52d6aab77d6e1f58f3f85ace7298d8a0?s=250&d=mm',
    title: 'We Want the Func!  Using Azure Functions to Ease Deployment',
    tags: ['.net','cloud','web'],
    level: 200,
    description: "Azure Functions allow you to write, deploy, and test code without worrying about where that code runs. Scalability, reliability, and server management are handled for you in this example of a 'serverless' technology, so that you can focus on the code. In this session, you will learn how to create, test, and deploy Azure functions; how to trigger them using REST calls, queues, database, and a scheduled interval; how to bind functions declaratively to other technologies; and how to create long-running durable transaction in Azure functions."
  },
   {
    time: '2019-05-11 10:45:00 AM',
    track: 'Practices',
    room: 7,
    topic: 'practices',
    speaker: 'Joe Hummel',
    image: 'https://secure.gravatar.com/avatar/4e0b64d9f107f00dde1ca5108f17d1da?s=250&d=mm',
    title: 'Functional Programming in a Nutshell',
    tags: ['.net'],
    level: 200,
    description: "Functional programming is not about the language, but about a mindset --- solving problems in a more mathematical way. In mathematics, the statement x = x + 1 makes no sense, yet in programming we use it all the time to change the state of x. Functional programming is about problem solving without directly changing the state of memory. This leads to 2 advantages: (1) a stronger sense of program correctness, and (2) an easier path to parallel execution. This talk will introduce functional programming in F#, show how to call F# from C#, and encourage you to adopt this mindset when it makes sense."
  },
   {
    time: '2019-05-11 01:00:00 PM',
    track: 'Practices',
    room: 7,
    topic: 'practices',
    speaker: 'Quinn Gil',
    image: 'https://secure.gravatar.com/avatar/c850fa503add812d9f608d8adf971930?s=250&d=mm',
    title: 'Technical Practices for Sustainable Code',
    tags: ['.net','java','mobile','ruby','testing'],
    level: 200,
    description: "Highly maintainable code is hard to produce. Object oriented code was supposed to enable us to write clean, understandable code - and yet... we're often stuck with incomprehensible code we can't get tests around. Most of this isn't good object oriented code. Good object oriented code is maintainable. Writing good object oriented code is hard. Without maintainability we can not have sustainable code, it will rot and have to be re-written. As an industry we're often given principles (DRY, SOLID, Abstraction, Code Reuse...) which sound great to have in out object oriented code. Knowing the principles is clearly not enough to enable us to write good object oriented code. We need some hands on keyboard deliberate practices that help us get there. I just happen to write my code using some technical practices that drive good object-oriented code. This talk goes into a few of technical practices I've found to have the biggest impact towards good object oriented code. Strictly applying just these practices will help the maintainability of the code. These technical practices produce simple, understandable, testable code which results in extremely maintainable code that we can work in to consistently and quickly deliver value to our customers."
 },
 
  {
    time: '2019-05-11 02:30:00 PM',
    track: 'Practices',
    room: 7,
    topic: 'practices',
    speaker: 'John Wright',
    image: 'https://secure.gravatar.com/avatar/85a588486bf00a2454d026a9bdf16e07?s=250&d=mm',
    title: 'Putting the Visual into the Visual Studio Debugger',
    tags: ['.net'],
    level: 200,
    description: "You've hit your Visual Studio breakpoint, opened the watch window and you're looking at a wall of nested collections and object graphs. You know the data you want is in there, but digging it out of the built-in data table UI feels like the 'doing it the hard way' part of an infomercial. Now, imagine being able to shape your data the way that makes it easiest to understand and debug, limited only by your imagination (and time, of course). In this session, we'll take a look at the Visual Studio Debugger Visualizer feature, available in all version of Visual Studio (even the free one!) that lets you create your own graphical display of your .NET data structures while debugging. Shape the data the way you want to make it easier to digest - hide unimportant info, quickly expose deeply nested elements, compare large object graphs, or even instantly search Stack Overflow for help with an Exception. Display it in whatever way is best for your data and your understanding of it, act on the data and even modify it from your custom view. We'll talk through the options available to you, some of the limitations, and security risks/considerations involved. This session doesn't require much deep knowledge of .NET, but the examples will primarily be in C#, WinForms and WPF. You don't need to know any of those beyond what you can Google or find on Stack Overflow, though the results will be useful to novices and well-weathered developers alike. (Note: While there is support for C++ visualizers, that won't be covered in this session.)"
 },
  
   {
    time: '2019-05-11 04:00:00 PM',
    track: 'Practices',
    room: 7,
    topic: 'practices',
    speaker: 'Steven Contos',
    image: 'https://secure.gravatar.com/avatar/f9776b5f4a9f2781d27a96ab5143646b?s=250&d=mm',
    title: 'Understanding and using Dependency Injection and Inversion of control',
    tags: ['.net'],
    level: 200,
    description: "Follow along as I start with everyone's classic introduction to programming and go nuts! Adding classes, interfaces, objects, logging to demonstrate the power of Dependency Injection and Inversion of Control without the overhead of other technologies such as MVC. We will also touch on cross cutting concerns and how they can be implemented using inversion of control. Updated for .net core."
 },
  {
    time: '2019-05-11 09:00:00 AM',
    track: 'Security',
    room: 3,
    topic: 'web',
    speaker: 'Chris Holland',
    image: 'https://secure.gravatar.com/avatar/2d5566e16f68126c93c15fc09139a54e?s=250&d=mm?s=250&d=mm',
    title: 'Practical Security in Web Applications',
    tags: ['dotnet','devops','security','web','java'],
    level: 100,
    description: 'Explore effective methods to identify & avoid the most common and devastating security pitfalls in Web Applications. When it comes to an enterprises exposure to security vulnerabilities, one could easily argue that its web presence is by far its greatest threat. There are many ways to build vulnerable applications and a few effective ways to "build them right". Well instrument you to stay on right side of this equation. Agenda: Basic Resources and Tooling ===================== * Well look at the OWASP Top 10 * Open-Source Code Analysis for your CI/CD * Open-Source Security Scanning Low-level Threat Avoidance ==================== * Avoiding SQL Injections -- Dangers of not properly-using an ORM * Avoiding CSRF * Avoiding XSS --- Data Scrubbing --- Data Rendering Application Threat Avoidance ===================== * User Authentication / Password Hashing * OAuth Security * Resource Access -- Multi Tenancy: Users & Companies'
  },
   {
    time: '2019-05-11 10:45:00 AM',
    track: 'Security',
    room: 3,
    topic: 'web',
    speaker: 'Johnathan "J." Tower',
    image: 'https://secure.gravatar.com/avatar/cf3d84705c47f78bdc8e91e8e4a9df61?s=250&d=mm',
    title: 'The Secrets of Multi-Tenant Applications with ASP.NET Core',
    tags: ['dotnet'],
    level: 200,
    description: "When you create an application that could have many different customers, it's important to think about how you've architected your application to ensure security and data consistency. In this session, we'll look at some useful tips and tricks for setting up a multi-tenant application using ASP.NET Core and Entity Framework Core. We'll look at lots of different strategies, including how to authenticate users, and identifying different tenants, global filters that prevent data from being show to the wrong tenant, soft deleting data, and even databases splitting strategies."
  },
  {
    time: '2019-05-11 01:00:00 PM',
    track: 'Security',
    room: 3,
    topic: 'web',
    speaker: 'Favian Eric Raygoza',
    image: 'https://secure.gravatar.com/avatar/4eabe061085e3098f4eda0f5a6aeda1d?s=250&d=mm',
    title: "Threat Model Express - Security In Your Software Development Cycle When You're Too Busy",
    tags: ['security'],
    level: 200,
    description: "Often, we're task to build fast and deploy fast. Its very hard to slow progress down for weeks of security reviews and implementation. What if we can find a way to implement security in (from the ground up) from the beginning of the software architecture phase? What if we can do this, without slowing down the agile development phase? In this session, we will explore how we can build the bridge between security and developer, to implement rapid and effective threat modeling; without slowing the project management process. This session will be very beneficial to Security Architects, Software Developers and Project Managers (as well as to anyone else who has to work on a team with these individuals). I will demonstrate the process to implement Threat Model Express into the software development life-cycle and bring all parties together, to meet in the middle at the crossroads of security and successful project planning."
  },
  
  {
    time: '2019-05-11 02:30:00 PM',
    track: 'Security',
    room: 3,
    topic: 'web',
    speaker: 'Micah Silverman',
    image: 'https://secure.gravatar.com/avatar/65aa21ea6e5c6ff3096dde98ddafd25c?s=250&d=mm',
    title: 'OAuth 2.0 and OpenID Connect (In Plain English)',
    tags: ['security','web','cloud'],
    level: 200,
    description: 'You’ve probably at least heard of the OAuth and OpenID Connect standards. It’s challenging to find a good overview of how they work. In this talk, Micah digs into these protocols in plain English, including a “Live Action OAuth Theater” segment in which volunteers act out a common OAuth interaction. Here’s the Live Action OAuth Theater segment of the talk (5 minutes): https://www.youtube.com/watch?v=NYzf2JBdUM8 We start with the foundations of federated and delegated authentication and authorization, work our way through concepts and foundations for OAuth and OIDC and end with some practical demonstrations of the standards in action.'
  },
  {
    time: '2019-05-11 04:00:00 PM',
    track: 'Security',
    room: 3,
    topic: 'security',
    speaker: 'Radif Masud',
    image: 'https://secure.gravatar.com/avatar/0c572f022d0ac83d70ccc1ca82c95463?s=250&d=mm',
    title: 'Got WAF?',
    tags: ['security','managment','cloud'],
    level: 200,
    description: "The age of cloud is here. Web Web all around and not a Web Application Firewall about? Get up and running on Cloudflare to secure web facing content and traffic. A layer 7 firewall that can be easily implented with no outage. Manage firewall rules and increase performance via next generation CDN. Oh you want to be serverless, let's talk about workers."
  },
  
  
  ]